mode: chatops
branchName: "issue-${issue.number}"
branches:
  # - label: enhancement
  #   prefix: feature/
  # - label: bug
  #   prefix: bugfix/
  # - label: ci
  #   prefix: ci/
  - label: "*"
    prefix: feature/
autoCloseIssue: true
commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
