name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/issue-${issue.number}'
  pull_request:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: yarn install, and build
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
          yarn run build --if-present
          yarn test
      
